### ISSUE TITLE
消息列表类似等级图标如果是网络图片怎么处理好呢

### ISSUE THREAD

**Issue by h-zhouwenjun** [QDong415/QLiveMessageHelper#1]

**Comment by QDong415** [comment]
方法1、收到消息后，进入子线程（我的demo中有），子线程中用glide同步下载图片，下载成功后，拼接spanString

方法2、如果整个项目中，对于每个主播的粉丝等级图片都是一样的，那么可以打开app的时候下载全部的等级图片到沙盒。然后收到消息的时候，从沙盒取图片
